model:
  model_name: "qwen_1p5b"
  base_model_name_or_path: "Qwen/Qwen2.5-1.5B"
  is_latent_reasoner: False

dataset:
  name: "open-r1/OpenR1-Math-220k"
  num_examples: 100000

training:
  seed: 42
  output_dir: "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra32qov2/latent_reasoner_storage/outputs/qwen_1p5b_sft"
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 64
  lr_scheduler_gamma: 0.8
  learning_rate: 5.0e-5
  lr_scheduler_step_size: 50
  num_train_epochs: 10
  logging_steps: 1
  eval_steps: 5120
  weight_decay: 0.01

wandb:
  project: latent_reasoner_sft
  run_name: qwen_1p5b_sft