import torch
from torch import nn
from typing import Any, Callable, Optional, Union

class LatentRLTrainer():

    def __init__(
        self, tokenizer, model, value_model, train_loader,
        reward_funcs: list, num_latent_steps: int, generation_config,
        args, device: str
    ) -> None:
        self.model = model
        self.value_model = value_model
        self.train_loader = train_loader
        self.reward_funcs = reward_funcs
        self.reward_func_names = []
        for i, _ in enumerate(reward_funcs):
            self.reward_func_names.append(reward_funcs[i].__name__)
        self.processing_class = tokenizer
        self.num_latent_steps = num_latent_steps
        self.generation_config = generation_config
        self.args = args
        self.device = device

    def _calculate_and_log_metrics(self):
        '''
        rewards
        estimated rewards by the value model
        responses generated by LatR
        also create a table for those stuff containing prompt, response, estimated reward, real reward
        '''
        pass

    def _generate_and_score_completions(self, inputs) -> dict:
        #### ASSUMPTION: We assume all completions in the batch have the same number of latent steps    ####
        #### and they are all at the beginning of the completion sequence                               ####
        #### If this doesn't hold, change this implementation                                           ####

        device = self.device

        prompts = inputs["prompt"]
        prompt_inputs = self.processing_class(
            text=prompts, return_tensors="pt", padding=True, padding_side="left", add_special_tokens=False
        )
        prompt_ids, prompt_mask = prompt_inputs["input_ids"].to(device), prompt_inputs["attention_mask"].to(device)

        # Generate completions using the model
        # This custom generate method from Latent reasoner returns:
        # 1) the completion token IDs for latent steps + language steps, no prompt
        # 2) and the embeddings for the prompt + latent steps + language steps
        completion_ids, prompt_completion_embeds = self.model.generate(
            prompt_ids, attention_mask=prompt_mask, 
            num_latent_steps=self.num_latent_steps,
            max_new_tokens=self.generation_config['max_completion_length'],
            temperature=self.generation_config['temperature'],
        )
        prompt_completion_embeds = prompt_completion_embeds.detach()

        # Compute prompt length and extract completion ids
        prompt_length = prompt_ids.size(1)
        prompt_embeds = prompt_completion_embeds[:, :prompt_length]
        completion_embeds = prompt_completion_embeds[:, prompt_length:]

        # Mask everything after the first EOS token
        is_eos = completion_ids == self.processing_class.eos_token_id
        eos_idx = torch.full((is_eos.size(0),), is_eos.size(1), dtype=torch.long, device=device)
        eos_idx[is_eos.any(dim=1)] = is_eos.int().argmax(dim=1)[is_eos.any(dim=1)]
        sequence_indices = torch.arange(is_eos.size(1), device=device).expand(is_eos.size(0), -1)
        completion_mask = (sequence_indices <= eos_idx.unsqueeze(1)).int()

        # Create another mask for latent steps since only they will be used for gradient calculation
        is_start = completion_ids == self.processing_class.start_latent_token_id
        is_end = completion_ids == self.processing_class.end_latent_token_id
        start_seen = is_start.cumsum(dim=1)
        end_seen   = is_end.cumsum(dim=1)
        inside_block = (start_seen >= 1) & (end_seen == 0)
        inside_block &= ~is_start
        latent_mask_completion = ((completion_ids == self.processing_class.latent_token_id) & inside_block).long()

        # ASSUMPTION: We assume all completions in the batch have the same number of latent steps
        assert latent_mask_completion.sum(dim=1).unique().numel() == 1, "All completions in batch should have same number of latent steps"

        # Add the zeros in the prompt and concat with latent_mask_completions to create is_latent_mask
        latent_mask = torch.cat([torch.zeros_like(prompt_ids), latent_mask_completion], dim=1)

        # Convert tensor to a list of lists of token IDs. This will be passed to the reward function, avoiding the need
        # to re-tokenize completions if the reward is computed from tokens.
        completion_ids_list = [
            [id.item() for id, m in zip(row, mask_row) if m] for row, mask_row in zip(completion_ids, completion_mask)
        ]

        # Decode the generated completions
        completions_text = self.processing_class.batch_decode(completion_ids, skip_special_tokens=True)

        rewards = {}
        for _, (reward_func, reward_func_name) in enumerate(
            zip(self.reward_funcs, self.reward_func_names)
        ):
                output_reward_func = reward_func(
                    prompts=prompts, completions=completions_text, completion_ids=completion_ids_list, answer=inputs['answer']
                )
                # Convert None values to NaN
                output_reward_func = [reward if reward is not None else torch.nan for reward in output_reward_func]
                rewards[reward_func_name] = torch.tensor(output_reward_func, dtype=torch.float32, device=device)

        return {
            "prompt_ids": prompt_ids,
            "completion_ids": completion_ids,
            "prompt_completion_embeds": prompt_completion_embeds,
            "latent_mask": latent_mask,
            "rewards": rewards
        }


    def train_step(self, inputs):
        # generate a response with LatR model
        ## this returns prompt and completion token ids and embeddings, rewards, mask (latent steps: 1, others 0)
        generation_results = self._generate_and_score_completions(inputs)
        
        # pass all the prompt+completion embeddings through the Value Model (tied with LatR model + value model head)
        values = self.value_model(inputs_embeds=generation_results["prompt_completion_embeds"])
        # freeze the value model head
        self.value_model.freeze_value_head()
        # calculate the loss for latent steps by taking the true class as reward = 1
        
        # backprop through the Value Model (so the LatR model is also updated)

    def train(self):
        
        epochs = self.args.get("training", {}).get("num_train_epochs", 1)
        for epoch in range(epochs):
            for batch in self.train_loader:
                self.train_step(batch)




